name: go-checks
on:
  pull_request:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repo
        uses: actions/checkout@v3
      - uses: Jerome1337/gofmt-action@v1.0.5
        name: check go fmt
        with:
          gofmt-path: './'
          gofmt-flags: '-l -d'
